### ISSUE TITLE
Crashing issue

### ISSUE THREAD

**Issue by CaptainAmpersand** [brainsynder-Dev/SimplePets#10]
### What steps will reproduce the problem?  
1. n/a 

### What were you expecting to happen? What happened instead?  
Be able to use without a crash... o.o
### What version of the plugin are you using? (Type /version &lt;Plugin Name&gt;)  
3.8
### What Spigot version are you using? (Type /version)  
git-Spigot-4bd94dc-aa34e9b (MC 1.12.2)
### What plugins are you using? (Type /plugins)  
http://i.nanonuke.net/javaw_2018-02-10_18-50-42.png
### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). (If you're not sure, upload your whole server log) 
Yes: https://hastebin.com/ahoyufamaf.swift
### Additional information?  *(Are you using a beta version of the plugin? Did it work in previous versions? etc.)*
Have seen my server crashing more and more recently -- However wasn't sure what was causing it.
I've seen issues when logging in/out in console, about ItemMovement, I believe. It's been happening more and more, and I'm just finally finding time to figure it out.

There is no way to reproduce it, really. It's morely just existing on my server has caused tons of crashes. I hope this can be fixed soon. I really want to implement this more into my server.

**Comment by brainsynder-Dev** [comment]
Your issue has already been fixed download here: https://discord.gg/qGfnAfC (Note: Requires the beta SimpleAPI as well)
