### ISSUE TITLE
error : null

### ISSUE THREAD

**Issue by ghost** [brainsynder-Dev/SimplePets#100]
### What steps will reproduce the problem?
1. spigot 1.16.5
2. use /pets
3. and see the error

https://pastebin.com/UZHtVwNQ
Spigot 1.16.5
Error with latest build

**Comment by brainsynder-Dev** [comment]
You reloaded the server/plugin (only way that error occurs)
Please turn off your server and turn it back on and it will be fixed.

**Comment by ghost** [comment]
already did => Stop / start server and the same problem

**Comment by brainsynder-Dev** [comment]
Can you send your latest.log file

**Comment by ghost** [comment]
[latest.log](https://github.com/brainsynder-Dev/SimplePets/files/6118805/latest.log)

**Comment by brainsynder-Dev** [comment]
Upgrade the version of SimplePets you have [DOWNLOAD HERE](https://ci.pluginwiki.us/job/SimplePets-Experimental/lastSuccessfulBuild/artifact/DIST/target/SimplePets.jar)

**Comment by ghost** [comment]
ty i try :)

**Comment by ghost** [comment]
Work fine !! =D ty <3
