### ISSUE TITLE
Shop won't work properly

### ISSUE THREAD

**Issue by NukaNilo** [brainsynder-Dev/SimplePets#102]
Hello.

I'm trying to set up simplepets where ppl go into the GUI and buy pets. I have Vault Installed, essentials eco, I also enabled economypet in the files, and also gave permission for the pet. the problem when testing  is that when the player goes into the GUI clicks on the pet it just spawns, no transaction is happening, they only have $22 and the pet cost $2k by default. what else do I need to do.

**Comment by Thatsmusic99** [comment]
Hi there, can you send your config.yml file? I spoke to someone last night about this and they didn't have the config fully set up. Cheers!

**Comment by NukaNilo** [comment]
Hey, thanks for the quick reply. I've been trying for two nights. 

Do you want me to just copy paste here? or send it to another way?

**Comment by Thatsmusic99** [comment]
Best done using a service like pastebin!

**Comment by NukaNilo** [comment]
https://pastebin.com/VJGg7bWy

**Comment by Thatsmusic99** [comment]
Aha, you may need to make vault uppercase, I believe the plugin makes it case sensitive.

**Comment by NukaNilo** [comment]
I think I tried, and just capital V. does number of spaces between semicolon matter? I can try again though.

**Comment by Thatsmusic99** [comment]
It all needs to be uppercase like VAULT so not just Vault. Please give that a try and let me know what that does! And I wouldn't say so but just have one space just in case.

**Comment by NukaNilo** [comment]
Now I feel like a dumbass haha, it worked, I swear I tried that lol. must have been half asleep or another configuration. thanks for the help appreciate that. last question.

 I need to give permission for each pet correct? like right now I only have the pig. in luckperms cause before it was just empty. just want to make sure im not doing it the hard way.

**Comment by Thatsmusic99** [comment]
Good to hear that and don't worry, sometimes we just make mistakes we don't usually expect!

If you want to give people every pet, then you can use the `Pet.type.*` permission or changing `Needs-Permission` in the config.yml to false. Otherwise, you give permission to the specific pets you want people to have.

**Comment by NukaNilo** [comment]
kk, thanks again, you just made my night, now I can focus on other stuff in here. Have a great day,

**Comment by Thatsmusic99** [comment]
No worries and happy to hear it! Have a nice day as well.
