### ISSUE TITLE
[BUG] Plugin makes citizens unusable with other plugins

### ISSUE THREAD

**Issue by arturek1666** [brainsynder-Dev/SimplePets#106]
Please drop the Debug.json file generated from doing `/pet debug` here

**Describe the bug**
If I install the plugin simplepets the npc interaction with other plugins don't work,
As example I have qshop and using NPC to open the shop if your plugin is on my server it doesn't work 

**Steps to reproduce**
1. Install citizens (any version will do as tested a couple
2. Install any plugin that interacts with NPC like plugin with gui in some kind that directly interacts with NPC:
Tested plugins:
Specilized crates - Can't open crate when clicking on npc
Qshop - Can't open any shop clicking on NPC 
3. Make sure you setup NPC and other interactive plugin with npc (Some plugins might work not tested all possible plugins) 

**Expected behaviour**
If plugin is installed it should not make other plugins stop interacting with citizens 

**Additional Information**
This was tested with fork version of plugin but also with paperspigot to make sure it's not a fork issue. 
Mc version 1.16.5
Tested with: #68 and maybe older ;) as i had older version updated and same issue.
Debug:
https://gist.github.com/arturek1666/bd2e6a6e85ee6f78e1a8c98675b0b1c0

**Comment by arturek1666** [comment]
While my last issue was false as it might be an issue with Minecraft engine itself, this issue was tested a lot to make sure I don't report false issues :) 
- Tested with 2 different plugins while citizens and simple pets was installed - The NPC could not be interacted
- Tested with 2 different plugins while citizens was installed without the plugin simple pets - All was working fine, I could interact with the NPC
- I had tested different Minecraft engine to make sure it's not a fork issue. 
- Debug has been provided 
- Trying to disable other plugins to see if it's maybe theirs issue but I had issue only when simple pets was installed
- Try different version of citizens but that didn't help either.

**Comment by brainsynder-Dev** [comment]
Let me remove Citizens from the `loadBefore` section in our plugin.yml (was added in the past to fix an issue with citizens interfering with the pets)

**Comment by brainsynder-Dev** [comment]
give [Build 69](https://ci.pluginwiki.us/job/SimplePets-Experimental/69/) a try please

**Comment by arturek1666** [comment]
:) if it's just the plugin.yml tweak I already edited my self, testing it now

**Comment by arturek1666** [comment]
Confirmed, removing the citizens from loadbefore has resolved the issue thank you
