### ISSUE TITLE
Riding Pets: Possibility to glitch through blocks (iron bars, glas panes etc.)

### ISSUE THREAD

**Issue by JOO200** [brainsynder-Dev/SimplePets#11]
### What steps will reproduce the problem?
0. Build a wall from iron_bars
1. Create a pet (e.g. Pig)
2. Stand close to the block. You have to be "in" the block (same coordinates as the block)
3. Click on the pet and choose "ride pet".
4. Go through the block

### What were you expecting to happen? What happened instead?
No possibility to glitch through the blocks.

### What version of the plugin are you using? *(Type /version <Plugin Name>)*
Simple-Pet version 3.9

### What Spigot version are you using? *(Type /version)*
Paper-Spigot 1.12.2 (Spigot 1.12.2-R0.1-SNAPSHOT)

### What plugins are you using? *(Type /plugins)*
BetonQuest, ChestShop, Citizens, Denizen, dynmap, iConomy, LWC, NoCheatPlus, Vault, WorldBorder, WorldEdit, WorldGuard (and some more self written)

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
No error.

### Are you using a beta version of SimplePets? *(If no, then please check if there is one [here](https://discord.gg/qGfnAfC) and give it a try)*: 
It's the version from yesterday on spigotmc.

### Additional information? *(Did it work in previous versions? etc.)*

Note: If you update your plugin, please update the version in the plugin.yml (e.g. 3.9.1).
You can use 3.9-SNAPSHOT to declare a snapshot version. ;)

**Comment by brainsynder-Dev** [comment]
From what I have tested (so far) it seems to only happen with small pets like the Rabbit and the baby chicken. I have not been able to do it with the pig (as said in example)
I will try and come up with a fix for this

As for your note, yea i know :P

**Comment by brainsynder-Dev** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix issue with pets glitching through walls](https://trello.com/c/WdO99ImJ/18-fix-issue-with-pets-glitching-through-walls)
