### ISSUE TITLE
Pets do not fly

### ISSUE THREAD

**Issue by teon56** [brainsynder-Dev/SimplePets#111]
### What steps will reproduce the problem?
1. paper 1.17 55
2. SimplePets_v5 Build 49

### What were you expecting to happen? What happened instead?

pets do not fly

### Could you please do *"/pet debug"* and paste the link here:

https://www.pastelog.us/uboqegepus

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*

No error

**Comment by brainsynder-Dev** [comment]
I am actually in the process of fixing this at the moment

**Comment by teon56** [comment]
Ok thx, i love your plugin and my player to, they were happy to hear that the compatible version 1.17 had arrived

**Comment by brainsynder-Dev** [comment]
Just putting this here, pets not being able to fly/jump was fixed a while ago in the latest builds
