### ISSUE TITLE
"Ride your pets" button

### ISSUE THREAD

**Issue by teon56** [brainsynder-Dev/SimplePets#112]
### What steps will reproduce the problem?
1. paper 1.17 55
2. SimplePets_v5 Build 49

### What were you expecting to happen? What happened instead?

When you disable 'All-Pets-Hat' in config, the button "Ride your pets" in /pets gui disappear to

### Could you please do *"/pet debug"* and paste the link here:

https://www.pastelog.us/pucawipeva

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*

No error

**Comment by brainsynder-Dev** [comment]
Will look into

**Comment by Thatsmusic99** [comment]
Not sure if this was fixed by one of many recent commits made by Brian but I am unable to reproduce this on v5 build 58.

**Comment by Thatsmusic99** [comment]
Yep, fixed in commit e5b88ac
