### ISSUE TITLE
Following v5 Build 49 - perms not working

### ISSUE THREAD

**Issue by James-Cotterill** [brainsynder-Dev/SimplePets#113]
Fixed in [v5 Build 49](https://ci.pluginwiki.us/job/SimplePets_v5/49/)

_Originally posted by @Thatsmusic99 in https://github.com/brainsynder-Dev/SimplePets/issues/110#issuecomment-869629356_

Hi,

Thank you so much for updating this and allowing us to use the plugin again.

Unfortunately there seems to be an issue with permissions as anyone can do /pet summon even when they don't have the perm set and the below enabled:

https://pastebin.com/6Sr0Hg9J

Also is there seems to be no limit on pets which is causing lag issues? Is there a way to make it so only one can be spawned at a time again#.

Thanks

**Comment by Thatsmusic99** [comment]
Everything mentioned in the issue above has been fixed as of [v5 build 52](https://ci.pluginwiki.us/job/SimplePets_v5/52/).
