### ISSUE TITLE
[BUG] java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "entity" is null

### ISSUE THREAD

**Issue by DrakMC** [brainsynder-Dev/SimplePets#115]
Please drop the link generated from doing `/pet debug` here
https://www.pastelog.us/tomukewugi

**Describe the bug**
After disconnecting from the server, this error is sometimes displayed: https://pastebin.com/raw/dLGBaGaq

**Comment by brainsynder-Dev** [comment]
Fixed in latest Jenkins [Build-66](https://ci.pluginwiki.us/job/SimplePets_v5/66/)
