### ISSUE TITLE
[BUG] org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled

### ISSUE THREAD

**Issue by DrakMC** [brainsynder-Dev/SimplePets#116]
Please drop the link generated from doing `/pet debug` here
https://www.pastelog.us/tomukewugi

**Describe the bug**
When shutting down the server, this error is displayed: https://pastebin.com/raw/6X9g9yX9

**Comment by Thatsmusic99** [comment]
Should be fixed in [v5 build 67](https://ci.pluginwiki.us/job/SimplePets_v5/67/)

**Comment by Thatsmusic99** [comment]
of course the plugin breaks as soon as I push the fix
