### ISSUE TITLE
Parrots don't keep their color on relog and server switch

### ISSUE THREAD

**Issue by Datdus** [brainsynder-Dev/SimplePets#12]
### What steps will reproduce the problem?
1. Switching servers
2. Going offline and rejoining

### What were you expecting to happen? What happened instead?
Keeping the set color for the parrot

### What version of the plugin are you using? *(Type /version <Plugin Name>)*
3.9

### What Spigot version are you using? *(Type /version)*
1.12.2-R0.1-SNAPSHOT

### What plugins are you using? *(Type /plugins)*
-

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
no

### Additional information? *(Did it work in previous versions? etc.)*
I don't know

**Comment by brainsynder-Dev** [comment]
This will be fixed in v4.0
