### ISSUE TITLE
[BUG] Error spam with latest worldguard addon

### ISSUE THREAD

**Issue by cloakfox** [brainsynder-Dev/SimplePets#127]
https://gist.github.com/cloakfox/29c4f7cb9f6dc192088d4255d8bdfd21

https://www.pastelog.us/dovurilezu

**Comment by Thatsmusic99** [comment]
Was /reload done with this? Since the `onEnable` event in the debug log (at `06:02:24`) does not fit with the times in the gist (`03:02:23` - mainly focusing on seconds here, hours are expected to be different in some scenarios).

**Comment by cloakfox** [comment]
No I never run /reload

**Comment by Thatsmusic99** [comment]
I'd be surprised if it happened without a reload, but regardless, there was a risk running for those errors anyways - I've just updated the addon to v0.4, does the same happen with that? You may have to restart the server to get rid of the old addon.

**Comment by cloakfox** [comment]
> I'd be surprised if it happened without a reload, but regardless, there was a risk running for those errors anyways - I've just updated the addon to v0.4, does the same happen with that? You may have to restart the server to get rid of the old addon.

Will try that one out and report back tomorrow.

Thanks!
