### ISSUE TITLE
Pets despawn immidiately

### ISSUE THREAD

**Issue by Lars-SparkMC** [brainsynder-Dev/SimplePets#128]
I downloaded your plugin and tried it on multiple servers but it didn't seem to work.
Whenever I try to spawn a pet it immediately disappears but I can see it a split second so I know it spawns.
My server isn't set to disable mob spawning or something like that I don't know what's wrong so please respond as soon as possible. :)

Thanks, Lars

**Comment by brainsynder-Dev** [comment]
just a note next time since this is an issue open a big report and not a question they have different formats and ask different questions which we need answers to to figure out the issue

Please send the link from /pet debug

**Comment by Thatsmusic99** [comment]
alright this is a problem we've largely covered in discord so if you're not gonna respond to brian, [please talk to us here instead about the issue so we can annoy you about the problem in real-time.](https://discord.gg/GSkB9QR9CC)
