### ISSUE TITLE
Flying mobs glitch

### ISSUE THREAD

**Issue by Datdus** [brainsynder-Dev/SimplePets#13]
### What steps will reproduce the problem?
1. flying

### What were you expecting to happen? What happened instead?
Non flying mobs should stay on the ground

### What version of the plugin are you using? *(Type /version <Plugin Name>)*
3.9

### What Spigot version are you using? *(Type /version)*
1.12.2

### What plugins are you using? *(Type /plugins)*
-

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
-

### Additional information? *(Did it work in previous versions? etc.)*
no

**Comment by brainsynder-Dev** [comment]
In the PetTranslator.yml simply turn off the "fly" option for the pets you dont want to be able to fly

**Comment by Datdus** [comment]
Thanks
