### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Knightrider1006** [brainsynder-Dev/SimplePets#130]
Please drop the link generated from doing `/pet debug` here

**Describe the bug**
when installed, i can an unknown internal error

**Steps to reproduce**
1. not sure
2. 
3. 

**Expected behavior**
it to work

**Screenshots/Videos (If you have any)**
![image](https://user-images.githubusercontent.com/95261205/144593670-9faa1efb-d203-4b96-95e3-8c18a2cd7383.png)

**Additional Information**
Add any other context about the problem here?

I'm not quite sure what the issue is, but i have a small list of plugins currently, so could any of these be conflicting and making something break? ive not touched none of its config or anything, this is right after install, any help on getting this fixed would be appreciated

**Comment by Thatsmusic99** [comment]
Do you mind sending your latest.log file here? There is no context whatsoever in this issue - no information on server version, type, plugin version, anything.

**Comment by Knightrider1006** [comment]
> Do you mind sending your latest.log file here? There is no context whatsoever in this issue - no information on server version, type, plugin version, anything.

sure thing
![image](https://user-images.githubusercontent.com/95261205/144601961-4f0fe20d-3559-40bb-bfa7-fca641a4c2d1.png)
[latest.log](https://github.com/brainsynder-Dev/SimplePets/files/7649550/latest.log)

**Comment by Thatsmusic99** [comment]
1.18 is not supported right now. We are still working on it but are stuck at this time.
