### ISSUE TITLE
[QUESTION] Can't edit Messages

### ISSUE THREAD

**Issue by inoshell** [brainsynder-Dev/SimplePets#131]
**Please put your question below**
I'm trying to translate the plugin for my servers lang. But every time I reload all of my translation disappears and old texts appear.
Also, I can't edit .class files for translating GUIs.
I'm waiting for your help.
Happy new Year!

**Comment by Thatsmusic99** [comment]
Is there an error you get when reloading the plugin?

What version of the plugin are you using?

What server type and version are you on?

**Comment by inoshell** [comment]
I am not getting any errors. When I reload the plugin, the messages.json file reverts to its original state.
Paper 1.17.1 Build 397

**Comment by brainsynder-Dev** [comment]
@KaptanINO You do not need to modify the .class files for the GUIs they have their own customization files located in the `plugins/SimplePets/Inventories/` folder

One way you could modify the `messages.yml` file is to modify the file... then you SHOULD be able to run the `/pet reload messages` command
IF that does not work then you could stop your server... then modify the messages... then you should just be able to start your server.

If that still does not work then send your `messages.yml` file and we will look into it

**Comment by inoshell** [comment]
Thanks for the feedback. If the messages.yml file is restored after translation, I will feedback.
Thanks for the help!
