### ISSUE TITLE
[Question]: 1.18.1 Will we see this goto 1.18.1 ?

### ISSUE THREAD

**Issue by Steev93** [brainsynder-Dev/SimplePets#133]
### Issue Related

NO

### What is your question?

1.18.1 Will we see this goto 1.18.1 ? Or should I look for another plugin?

### Did you search on Github?

- [X] I have searched on github

### Did you search on Discord?

- [X] I have searched on discord

**Comment by Thatsmusic99** [comment]
Well, that's covered in #132. Yes.

**Comment by Steev93** [comment]
Thanks could not find this on Spigot at all for the update i just found it before.
