### ISSUE TITLE
[Bug]: Pets don't transfer between worlds

### ISSUE THREAD

**Issue by OfficialTheosis** [brainsynder-Dev/SimplePets#136]
### Debug Log

The paste was too big for pastebin :( but I don't think the debug log is relevant for this case anyway (I'll get it to you another way if I'm wrong)

### What happened?

When a player travels between worlds via teleporting of any kind (portals, commands, etc.), any pets they have summoned will stay where they are and not do anything until the player returns to that world, at which point the pet will teleport to them.

### Steps To Reproduce

1. Summon at least one pet
2. Teleport to another world, such as the Nether or the End, or another overworld
3. Notice the pet is not with you, and check with another player to see that the pet is just standing there in the previous world

### Up-To-Date

- [X] I am using the latest build

**Comment by brainsynder-Dev** [comment]
Just letting you know the debug link didnt have to be put on pastebin...
When you type `/pet debug` it gives you a link already ;)

**Comment by OfficialTheosis** [comment]
> Just letting you know the debug link didnt have to be put on pastebin... When you type `/pet debug` it gives you a link already ;)

Oh... I didn't see that when I did it the first time, I only saw the message about the newly created JSON file in the /SimplePets/ directory. Might have been an issue with my shared host console - sometimes it doesn't output things that it should. :(

Here is a new debug link: https://www.pastelog.us/ezejakigex

**Comment by brainsynder-Dev** [comment]
Was fixed in [build: 112](https://ci.pluginwiki.us/job/SimplePets_v5/112/)
