### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Ronal1999** [brainsynder-Dev/SimplePets#145]
### Debug Log

cannot upload it, too heavy 

### What happened?

Send errors in console when I spawn a pet 1.17.1 paper spigot

### Steps To Reproduce

1: Open Gui
2: Select a PET
3: Change it

### Relevant log/error output

```shell
https://pastebin.com/Q3aMTunm

https://pastebin.com/bNi1Br87
```

### Up-To-Date

- [X] I am using the latest build

**Comment by brainsynder-Dev** [comment]
These issues have been fixed in the latest build [126](https://ci.pluginwiki.us/job/SimplePets_v5/126/)
The issue https://pastebin.com/bNi1Br87 has been fixed in a new build of the WorldGuard Addon
