### ISSUE TITLE
[Feature Request]: Update Treasury Integration

### ISSUE THREAD

**Issue by lokka30** [brainsynder-Dev/SimplePets#147]
Treasury v1.1.0 has released which changes the way that economy providers are accessed - instead of using Bukkit's service manager, plugins should now use Treasury's service API to access it. Let me know if you need a hand with it :smiley:

**Comment by brainsynder-Dev** [comment]
![Capture](https://user-images.githubusercontent.com/25085442/154401106-a73f8c68-6437-4439-b146-b15722257cf4.PNG)
I have updated the [Treasury Addon](https://github.com/BSDevelopers/TreasuryAddon)
