### ISSUE TITLE
Allow customisation of MySQL pool size

### ISSUE THREAD

**Issue by Foorack** [brainsynder-Dev/SimplePets#18]
Feature request. Current value is hard-coded to 10.

https://github.com/brainsynder-Dev/SimplePets/blob/master/src/main/java/simplepets/brainsynder/database/MySQL.java#L22

**Comment by brainsynder-Dev** [comment]
Added in commit: [38faef4](https://github.com/brainsynder-Dev/SimplePets/commit/38faef421713e3153246de823681526ec0d36dcc)
