### ISSUE TITLE
[Bug]: Players can move in residence with the move flag on false

### ISSUE THREAD

**Issue by DrakMC** [brainsynder-Dev/SimplePets#181]
### Debug Log

https://www.pastelog.us/dazihuhuqo

### What happened?

Players can move in a foreign residence that has its move flag set to false.

### Steps To Reproduce

1. Go outside the residence
2. Pick a pet and ride on it
3. Ride to the residence where move is set to false.

### Up-To-Date

- [ ] I am using the latest build

**Comment by Thatsmusic99** [comment]
Appears to be associated with Residence, if they have an API we'll get an addon made for it.

**Comment by brainsynder-Dev** [comment]
Ok I just pushed a SimplePets addon that adds support for [Residence](https://www.spigotmc.org/resources/11480/)
I need you to do a few things...

1. Update your version of SimplePets  as you are using an old version and the addon wont work for it
2. Install the Residence Addon... You can do it via `/pet addon install Residence` or follow any of the instructions on the [WIKI](https://wiki.bsdevelopment.org/pet-addons/addon-faq#how-can-i-install-addons-for-simplepets)

**_Note:_** This addon was not tested as neither of us have Residence or CMI installed/configured on our test servers... So please report any issues you have with this addon [HERE](https://github.com/BSDevelopers/ResidenceAddon/issues/new)

Please respond back here if it has helped you

**Comment by DrakMC** [comment]
It's working, thanks

**Comment by DrakMC** [comment]
File AddonConfig.yml will reset after each startup. So it doesn't work after server restart. Please fix it.

**Comment by brainsynder-Dev** [comment]
> File AddonConfig.yml will reset after each startup

That file is not ment to be customized... It is there to store what addons are enabled

All addon configs are in the `plugins/SimplePets/Addons/configs`

**Comment by DrakMC** [comment]
I'm not editing this file. It resets every restart.

**Comment by Thatsmusic99** [comment]
With this in mind, is it disabling the addon? Was a bit confused but does make more sense if that is the case.

**Comment by DrakMC** [comment]
It remove all addons when restarting server.

**Comment by DrakMC** [comment]
Any solution?

**Comment by Thatsmusic99** [comment]
Hm... that is a bizarre issue but I haven't come across it in my own test files. Can I ask if you have either your latest.log or debug file handy for when the server starts, after adding an addon?

**Comment by DrakMC** [comment]
Debug file: https://pastebin.com/raw/qabpPHXx

**Comment by Thatsmusic99** [comment]
I don't see Residence anywhere in your plugins list, is it loading properly?

**Comment by DrakMC** [comment]
Yes, it is loaded properly.

**Comment by Thatsmusic99** [comment]
In this instance it looks like it didn't load properly since it isn't included in the debug plugin list. The next time the server restarts and the addon doesn't appear, can you ensure the plugin fully starts up?

**Comment by DrakMC** [comment]
![image](https://user-images.githubusercontent.com/40771376/174823291-a00d2604-3007-4a67-8d56-0703780499d5.png)
I can't install any addon. It says it's downloading, but nothing is downloaded.

**Comment by brainsynder-Dev** [comment]
What @Thatsmusic99 was saying before was that the Residence plugin is not in your plugin list
as seen in the list of plugins in your debug link...
![UOb5ICg](https://user-images.githubusercontent.com/25085442/175104795-e5a82bb2-9f3f-4955-a6ce-2ec88e15ca82.png)

The addon is already installed and enabled according to the paste you sent
![loaded-addons](https://user-images.githubusercontent.com/25085442/175105093-0ee99601-e6e6-4a35-90fb-ed628d84747c.PNG)
