### ISSUE TITLE
Maven doesn't work

### ISSUE THREAD

**Issue by Foorack** [brainsynder-Dev/SimplePets#2]
I see there is a maven pom.xml but it doesn't actually do anything.
If you try compile the project with `mvn package` then it just ends with "No sources to compile".
The project also isn't structured correctly. :confused: 

https://maven.apache.org/guides/getting-started/

Biggest problem is that you need all the different version of the the minecraft jars to compile, which aren't  legally allowed to distribute. Best would be if you could instead use reflection to access NMS

**Comment by Foorack** [comment]
@brainsynder-Dev Why was this closed? Maven is still not configured correctly, and is still producing empty jar files.
![ekrankopio de 2018-03-01 21-34-57](https://user-images.githubusercontent.com/5008081/36868396-7b4f5144-1d98-11e8-835d-070dce2f8ce3.png)

**Comment by brainsynder-Dev** [comment]
It works perfectly fine on our end, We cant really use Reflection for all the NMS so that is why we use the CraftBukkit Jars locally.
If the pom.xml is not configured properly then what do you think is wrong, because as I have said it works perfect for us?

**Comment by brainsynder-Dev** [comment]
nvm I just noticed your edit... this will be fixed.
