### ISSUE TITLE
Pet fails to follow player after switching servers with Bungee

### ISSUE THREAD

**Issue by lekro** [brainsynder-Dev/SimplePets#20]
### What steps will reproduce the problem?
1. Summon pet in one server
2. Switch to other server, e.g. using `/server`
3. Switch back to the server in which the pet was summoned

### What were you expecting to happen? What happened instead?
Pets will normally follow the player and teleport to the player when summoned with `/pet summon PET`. But when the player switches servers and switches back, the pet seems to be always summoned to the spot the player was last in before switching servers and doesn't follow the player as it should. Attempting to ride the pet teleports the *player* to the pet, and the only way to get the pet to move seems to be to use it as a hat or vehicle. After dismounting/removing it from hat, the pet teleports to the same spot to which it keeps getting summoned.

Removing and resummoning the pet results in the same behavior. The only workaround is to remove the pet, switch servers, switch back, and then resummon the pet. Then the pet behaves as normal, following around the player and teleporting to the player when summoned.

### What version of the plugin are you using? *(Type /version <Plugin Name>)*
Compiled from commit 7f2a908

### What Spigot version are you using? *(Type /version)*
`git-Paper-1299 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

### What plugins are you using? *(Type /plugins)*
SimplePets, any teleportation plugin

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
Nothing

### Are you using a beta version of SimplePets? *(If no, then please check if there is one [here](https://discord.gg/qGfnAfC) and give it a try)*: 
Using latest commit to `master`

### Additional information? *(Did it work in previous versions? etc.)*
Didn't work in SimplePets 3.9 (simpleAPI 3.8)

**Comment by Thatsmusic99** [comment]
An issue similar to this was reported and should be fixed in the next version (v4.0).
