### ISSUE TITLE
[Feature Request]: Make addons lore multiline

### ISSUE THREAD

**Issue by Josh65-2201** [brainsynder-Dev/SimplePets#206]
### Issue Related

YES

### Addon

- [ ] Yea, it could be an addon instead

### Describe the Feature

Currently the lores are too long and mean most of them go off screen
![image](https://user-images.githubusercontent.com/26977075/191293267-f7f8cd4b-4c1c-45aa-bda5-040582d78f00.png)

**Comment by brainsynder-Dev** [comment]
This mostly depends on the GUI Scale your minecraft is set to (For example my GUI Scale is set to `2` and I can see them just fine)
We could possible try and add some code to the plugin to split the lines after so many characters...

**Comment by Josh65-2201** [comment]
I need to have my GUI scale 1 to see the full thing and it not usable.
![image](https://user-images.githubusercontent.com/26977075/195997501-2b0dffad-1e75-4645-b47d-63ddeaf78842.png)

**Comment by brainsynder-Dev** [comment]
Currently working on this at the moment
This is what it looks like with the highest GUI Scale (4x and auto)
![image](https://user-images.githubusercontent.com/25085442/196007450-d0afa6e2-098a-4a9b-9d62-f8d2b952dce0.png)
