### ISSUE TITLE
[Bug]: Not Compiling Properly. (This could be my fault)

### ISSUE THREAD

**Issue by AaravDugar** [brainsynder-Dev/SimplePets#208]
### Debug Log

Compile Error

### What happened?

I tried to compile the 1.17.1 version and I followed apache's instructions. I expected it to run but it just gave me a **BUT TON OF ERRORS**.

### Steps To Reproduce

1. Do the normal (Install maven, Get the src and extract in the BIN folder)
2. Run the command mvn or the command that they give

### Relevant log/error output

```shell
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'artifactId' contains an expression but should be a constant. @ line 13, column 17
[WARNING] 'version' contains an expression but should be a constant. @ line 11, column 14
[FATAL] Non-resolvable parent POM for simplepets.brainsynder:Version_${minecraft.version}:${module.version}: Could not find artifact simplepets.brainsynder:SimplePets:pom:1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project simplepets.brainsynder:Version_${minecraft.version}:${module.version} (D:\Downloads\maven\apache-maven-3.8.6\bin\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for simplepets.brainsynder:Version_${minecraft.version}:${module.version}: Could not find artifact simplepets.brainsynder:SimplePets:pom:1.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

### Up-To-Date

- [X] I am using the latest build

**Comment by Thatsmusic99** [comment]
Have you compiled the parent project as well? 
```
Could not find artifact simplepets.brainsynder:SimplePets:pom:1.0-SNAPSHOT
```

**Comment by brainsynder-Dev** [comment]
Just to be sure you are running this maven command right?
`mvn clean install -f pom.xml`

**Comment by AaravDugar** [comment]
> Have you compiled the parent project as well?
> 
> ```
> Could not find artifact simplepets.brainsynder:SimplePets:pom:1.0-SNAPSHOT
> ```

Huh? What do you mean?

**Comment by AaravDugar** [comment]
> Just to be sure you are running this maven command right? `mvn clean install -f pom.xml`

Yes, I am using the clean install one.

**Comment by Thatsmusic99** [comment]
> Huh? What do you mean?

By that I mean compile from the parent directory rather than just the 1.17.1 one.

**Comment by AaravDugar** [comment]
> > Huh? What do you mean?
> 
> By that I mean compile from the parent directory rather than just the 1.17.1 one.

Oh... Will try

(Edit) I'm trying it now

**Comment by AaravDugar** [comment]
> > > Huh? What do you mean?
> > 
> > 
> > By that I mean compile from the parent directory rather than just the 1.17.1 one.
> 
> Oh... Will try
> 
> (Edit) I'm trying it now

It Worked and compiled!

I will close this issue now.
