### ISSUE TITLE
[Question]: how much time should it take to decompile and recompile?

### ISSUE THREAD

**Issue by AaravDugar** [brainsynder-Dev/SimplePets#209]
### Issue Related

NO

### What is your question?

I have been waiting for it to decompile and recompile for ~5mins now. No other java compilation has taken this long for me.

My internet is decent and disk speeds are good.

I have to go somewhere in about 5 mins now and am waiting for it to finish.
Could you tell me how much time it usually takes?

Thanks

### Did you search for answers?

- [ ] I have searched on [GITHUB](https://github.com/brainsynder-Dev/SimplePets/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for similar answers
- [ ] I have searched on [DISCORD](https://discord.gg/TzhnW8xtsR) for answers
- [x] I have searched the [WIKI](https://brainsynder.gitbook.io/simplepets/faq) for answers

**Comment by AaravDugar** [comment]
Also, Can I close CMD midway? If I can, it will be great and if I cant, I will have to wait

**Comment by AaravDugar** [comment]
It took a good 10 minutes but, it is done!

**Comment by brainsynder-Dev** [comment]
Yea it takes a while to compile...
