### ISSUE TITLE
Players specifying their own username in summon command uses pet.summon.other node

### ISSUE THREAD

**Issue by lekro** [brainsynder-Dev/SimplePets#21]
This one is just me being pedantic, sorry ;)

### What steps will reproduce the problem?
1. Give yourself permission to use a blaze pet (`pet.blaze`)
2. `/pet summon blaze` will work, uses permission node `pet.blaze`
3. `/pet summon blaze your_username` will not work, uses permission node `pet.summon.other`

### What were you expecting to happen? What happened instead?
The behavior should be similar to the UNIX `passwd` command, which accepts an optional argument of `USER`, and will allow a user to change its own password with `passwd` or `passwd $USER`.

Instead, specifying a user always leads to using permission node `pet.summon.other`.

### What version of the plugin are you using? *(Type /version <Plugin Name>)*
Compiled from commit 7f2a908

### What Spigot version are you using? *(Type /version)*
`git-Paper-1299 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)`

### What plugins are you using? *(Type /plugins)*
SimplePets, LuckPerms

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
Nothing

### Are you using a beta version of SimplePets? *(If no, then please check if there is one [here](https://discord.gg/qGfnAfC) and give it a try)*: 
Using latest commit to `master`

### Additional information? *(Did it work in previous versions? etc.)*
Didn't work in SimplePets 3.9 (simpleAPI 3.8)

**Comment by brainsynder-Dev** [comment]
This will be fixed in v4.0 of SimplePets
