### ISSUE TITLE
[Bug]: Pets don't walk

### ISSUE THREAD

**Issue by Nononitas** [brainsynder-Dev/SimplePets#212]
### Debug Log

https://www.pastelog.us/paste/CEBHJDAGIFK

### What happened?

Pets will only teleport when out of range and will not walk alongside you. So they don't move at all
Config: https://pastebin.com/Gz2ip0tE

### Up-To-Date

- [X] I am using the latest build

**Comment by Nononitas** [comment]
-

**Comment by brainsynder-Dev** [comment]
Ok... so the pets do not walk after the player/pet teleports...
if thats what im seeing here...

**Comment by Nononitas** [comment]
No if you walk the pet just teleports and is not walking beside you
