### ISSUE TITLE
[Bug]: NoClassDefFoundError when renaming pet

### ISSUE THREAD

**Issue by daniel-skopek** [brainsynder-Dev/SimplePets#220]
### Debug Log

https://pastebin.com/raw/FBz9axQM

### What happened?

You can't rename a pet. AnvilGUI will not open.

### Up-To-Date

- [ ] I am using the latest build

**Comment by Thatsmusic99** [comment]
May be covered by #219 @brainsynder-Dev ?

**Comment by daniel-skopek** [comment]
Yeah, exactly
