### ISSUE TITLE
Cannot change the prefix

### ISSUE THREAD

**Issue by Nacholebraa** [brainsynder-Dev/SimplePets#23]
I cannot change the prefix for the plugin it is stuck with '{Prefix}'

**Comment by Thatsmusic99** [comment]
Had this submitted a while ago but really we can't see what's wrong. Will test it now. Can you tell us your server version and type (Spigot, PaperSpigot, etc)?

**Comment by Nacholebraa** [comment]
We use Spigot 1.12.2

**Comment by Nacholebraa** [comment]
Actually now its working ..... idk whatever you guys did it worked. I can post screenshots of what it was looking like before? if you want. I changed all of the variables that were default to what I wanted as the prefix and just manually inserted the prefix into the message and removed the set prefix. If you guys didn't do any thing that is what I did.

**Comment by brainsynder-Dev** [comment]
We didnt do anything :P

**Comment by Thatsmusic99** [comment]
And that's the even creepier bit.

**Comment by Nacholebraa** [comment]
![2018-05-31_10 38 47](https://user-images.githubusercontent.com/36382273/40788807-e8f04fa6-64be-11e8-86ba-8b33eefd5b2c.png)
![2018-05-31_10 38 55](https://user-images.githubusercontent.com/36382273/40788808-e904625c-64be-11e8-883a-6ac1b301850b.png)

**Comment by Nacholebraa** [comment]
The first is what it was saying in chat and the second is the fix statment then...

**Comment by Nacholebraa** [comment]
I guess thanks for the help xD

**Comment by brainsynder-Dev** [comment]
No problem :P (I guess XD)
