### ISSUE TITLE
Pets wont Respawn when player loads back in

### ISSUE THREAD

**Issue by ZombieSkull** [brainsynder-Dev/SimplePets#25]
### What steps will reproduce the problem?
1.give player simple pet
2.they log off server
3. pet doesnt respawn

### What were you expecting to happen? What happened instead?
the config file says the true for pet respawn when play logs on, but they dont respawn
### What version of the plugin are you using? *(Type /version <Plugin Name>)*
version 3.8
### What Spigot version are you using? *(Type /version)*
spigot 1.12.2
### What plugins are you using? *(Type /plugins)*
SimpleAPI, Vault, GriefPrevention, SimplePets, GroupManager, Citizens, Essentials, EssentialsProtect, EssentialsSpawn, EssentialsChat
### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
no i do not

**Comment by Thatsmusic99** [comment]
Please try using the latest beta version: https://ci.athion.net/job/SimplePets/12/ or to keep up to date with them, https://discord.gg/qGfnAfC
