### ISSUE TITLE
[Bug]: Cannot spawn pets

### ISSUE THREAD

**Issue by daniel-skopek** [brainsynder-Dev/SimplePets#254]
### Debug Log

https://pastebin.com/raw/gg4cfjCj

### What happened?

When I spawn pet, this error is thrown: https://pastebin.com/raw/nM54rddK

### Up-To-Date

- [X] I am using the latest build

**Comment by brainsynder-Dev** [comment]
Can you try and poin-point what plugin is conflicting...
I have tested this on my TestServer with only Essentials, ViaVersion, ViaBackwards, and SimplePets... And I have no issues...

**Comment by daniel-skopek** [comment]
Tried on the latest version of Pufferfish with no other plugins. The issue is still persists.

![image](https://github.com/brainsynder-Dev/SimplePets/assets/117641078/69477905-5e29-4b80-b17e-7ed2b6126a94)

1. /pet gui
2. Summon pet by clicking on it in the GUI
3. Error appears in the console

**Comment by brainsynder-Dev** [comment]
This is another one of those cases where I cant reproduce it...
I might have a way i can fix it and i could just do a check in the CitizensFixer to check if Citizens is actually installed

![image](https://github.com/brainsynder-Dev/SimplePets/assets/25085442/366aea3a-df79-4b96-b385-195d976b1a8f)

**Comment by brainsynder-Dev** [comment]
Latest jenkins build fixes this issue
