### ISSUE TITLE
1.12.2 Pets not pawning!

### ISSUE THREAD

**Issue by JoshuaHotchin** [brainsynder-Dev/SimplePets#26]
### What steps will reproduce the problem?
Only pet that spawns is armor stand, I am opped and the only pet that spawns is the armor stand. I thought it was because of the WorldGuard region permission but it is not! 

### What were you expecting to happen? What happened instead?
I was expecting the pet to spawn, it didn't.

### What version of the plugin are you using? *(Type /version <Plugin Name>)*
4.0

### What Spigot version are you using? *(Type /version)*
git-Spigot-c309ef-aa25568
Implemting API 1.12.2-R0.1-SNAPSHOT
MC version 1.12.2

### What plugins are you using? *(Type /plugins)*
Plugins (32): WorldEdit, OpenInv, BuycraftX, Votifier, WorldGuard, EasyPlayerHeads, SuperTrails, EpicBalloons, RewardVoting, EditableSign, Vaults, PermissionsEx, SimpleAPI, Vault, ChatColor, TitleManager, NoSwear, Essentials, Rankup, SimplePets, EssentialsProtect, EssentialsChat, CrazyAuctions, Animated_Soreboard, EssentialsSpawn, PlotSquared, Multiverse-Core, MineResetLite, Multiverse-Portals, HolographicDisplays, CratesPlus, InventoryFull

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
https://hastebin.com/ukotomagez.sql

### Are you using a beta version of SimplePets? *(If no, then please check if there is one [here](https://discord.gg/qGfnAfC) and give it a try)*: 
^^^Discord link didn't work!

**Comment by JoshuaHotchin** [comment]
I would like to point out that 1. I am a special spud. and 2. After restarting the server (NOT RELOADING) the pets worked!

**Comment by Thatsmusic99** [comment]
Marking this as closed as you now say the pets work.
