### ISSUE TITLE
[Bug]: Cannot spawn pets 1.20.6

### ISSUE THREAD

**Issue by TwoPointInfinity** [brainsynder-Dev/SimplePets#261]
### Debug Log

https://www.pastelog.us/paste/DJHBFKACIEG

### What happened?

![image](https://github.com/brainsynder-Dev/SimplePets/assets/7976722/85cc74ec-1d72-4170-a73b-d53ba5b2a01c)
ok, i download the file for 1.20.6 and then update simplepets.
no more error in chat, but pets cannot spawn. 
![image](https://github.com/brainsynder-Dev/SimplePets/assets/7976722/4b521081-36d2-4e11-bec3-fe8c2e8ed2b2)

### Steps To Reproduce

using the versions shown, try and spawn a pet with /pets gui

### Relevant log/error output

```shell
https://www.pastelog.us/paste/FCAJGEHKIBD
```

### Up-To-Date

- [X] I am using the latest build

**Comment by TwoPointInfinity** [comment]
Constant console spam while the server runs also.

**Comment by TwoPointInfinity** [comment]
here's a link to the error that logs when i try to spawn the elder_guardian 
https://pastebin.com/FAfUaye9

**Comment by brainsynder-Dev** [comment]
Im loading up my console finally... will let you know if i find anything

**Comment by brainsynder-Dev** [comment]
![image](https://github.com/brainsynder-Dev/SimplePets/assets/25085442/7c89e56c-4e2f-4ad2-a6e6-bbfdb3d399d9)
Hmmmmm I was able to spawn pets fine on the same Paper version... leme check if its an issue with the jar you downloaded gimme a bit

**Comment by TwoPointInfinity** [comment]
Thank you for such a quick response, if there's anything I've done wrong, like downloaded the wrong jar please allow me to download the correct one.

**Comment by brainsynder-Dev** [comment]
Ahhhhh i found the actual reason for this...
Paper is using the Mojang Mappings where we use the obfuscated field names in our code...

Might need to change that around a bit (damn it Paper...)
