### ISSUE TITLE
[Feature Request]: Configurable Entity Sizing

### ISSUE THREAD

**Issue by mrsqueak11806** [brainsynder-Dev/SimplePets#262]
### Issue Related

NO

### Addon

- [X] Yea, it could be an addon instead

### Describe the Feature

I think it would be prudent to add a config option to change the size of the entities. Both a blanket resize via percentage in the main config and a per pet option. Maybe even let the players determine how small/large the pet is via the gui, limited by the max size in the config of course. Great plugin.

**Comment by brainsynder-Dev** [comment]
tbh i completely forgot about this feature being added :P
I will have to see what we can do with it

**Comment by brainsynder-Dev** [comment]
Working on a little something...
![image](https://github.com/brainsynder-Dev/SimplePets/assets/25085442/5ed7b617-f7d4-4352-bd6c-eb5ca6721bc9)

**Comment by mrsqueak11806** [comment]
omg i <3 it!
