### ISSUE TITLE
[Bug]: Pets dont walk/pathfind 1.20.6

### ISSUE THREAD

**Issue by TwoPointInfinity** [brainsynder-Dev/SimplePets#263]
### Debug Log

https://www.pastelog.us/paste/KDCEIJBGHAF

### What happened?

Spawned pets arent following the owner by walking.
Ridable pets also dont step up blocks if they are intended to, this may be unrelated.

I have gotten the allay to walk bu spawning it AGAIN while its already spawned, but this doesn't work for all pets.

### Steps To Reproduce

using 1.20.6, spawn a pet
walk around, pet doesnt follow. 
pet instead teleports near owner, every 5 blocks.

### Up-To-Date

- [x] I am using the latest build

**Comment by TwoPointInfinity** [comment]
some extra information is that i've gone to every flyable pet and disabled their fly in their config.

**Comment by brainsynder-Dev** [comment]
strange... will have to look into this one as i didnt have this issue

**Comment by TwoPointInfinity** [comment]
if you cant reproduce i can provide my configs

**Comment by TwoPointInfinity** [comment]
i reset my configs, and the issue was fixed.
