### ISSUE TITLE
I cannot complete the pet shop feature for members in the server

### ISSUE THREAD

**Issue by Khanguyen2506** [brainsynder-Dev/SimplePets#267]
### Debug Log

The log has no error but the pet shop feature doesn't work

### What happened?

I have tried editing every config included in the plugin. I also installed the plugin's addon. And then I edited each line of code in the config but it still doesn't work with the feature of buying pets with playerpoint. My server version is paper 1.20.6. Can you help me set up the pet shop feature for my server?

### Up-To-Date

- [X] I am using the latest build

**Comment by brainsynder-Dev** [comment]
Sorry for the delay, As soon as the addon is installed it is recommend to restart the server for it to enable properly.
Your players will need to have permission to the pets you want them to be able to purchase
