### ISSUE TITLE
Kicking Multiple People Off!

### ISSUE THREAD

**Issue by Sav1018** [brainsynder-Dev/SimplePets#27]
### What steps will reproduce the problem?
1. selecting a horse pet
2. toggling to ride
3. riding on it

### What were you expecting to happen? What happened instead?
I was expecting to be able to ride the horse pet without it causing issues. What happened instead was it kicked off everyone on the island with me, myself included, as well as no longer allowing me to connect through my main account. Anytime I attempt to reconnect, it shows the message "Disconnected" then kicks the people on the island off again.
### What version of the plugin are you using? *(Type /version <Plugin Name>)*
SimplePets version 3.9
### What Spigot version are you using? *(Type /version)*
[https://media.discordapp.net/attachments/271774727939424257/472999986104107009/Screen_Shot_2018-07-29_at_12.32.28_AM.png](url)
### What plugins are you using? *(Type /plugins)*
[https://cdn.discordapp.com/attachments/271774727939424257/473000230954991626/Screen_Shot_2018-07-29_at_12.33.48_AM.png](url)
### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
I don't, I was unaware that I would need to contact someone about this, but no one was able to help then directed me here.
### Additional information? *(Did it work in previous versions? etc.)*

**Comment by brainsynder-Dev** [comment]
Have you tried out v4.0?
I seem to be unable to reproduce this issue...
