### ISSUE TITLE
[Bug]: For input string: "%%__RESOURCE__%%"

### ISSUE THREAD

**Issue by Runkang10** [brainsynder-Dev/SimplePets#274]
### Debug Log

Can't generate link for unexpected errors while executing that command

### What happened?

Unable to enable the plugin:
![image](https://github.com/user-attachments/assets/8e9b57b4-29e3-4793-b774-b2f7c2595fae)

### Steps To Reproduce

1. Install the plugin
2. Start server
3. Check plugin status

### Up-To-Date

- [x] I am using the latest build

**Comment by Runkang10** [comment]
All plugin commands are not available because the plugin is disabled.

**Comment by brainsynder-Dev** [comment]
By chance, where did you download the plugin from?
If you downloaded the plugin from :
- `Hangar (Paper)` 
- `Polymart`
- `Modrinth`

Then re-download the plugin, I forgot to change a value in one of the property files
I did re-upload those files with the correct changes

**Comment by Runkang10** [comment]
From Modrinth i downloaded.

**Comment by Runkang10** [comment]
I tried in Hangar with **5.0-BUILD-270** but still not working. I also removed the folder and reinstalled it.
