### ISSUE TITLE
[Bug]: Console error when renaming pets 

### ISSUE THREAD

**Issue by Momshroom** [brainsynder-Dev/SimplePets#275]
### Debug Log

https://www.pastelog.us/paste/BAHFJCGEDKI

### What happened?

When attempting to rename a pet, either via command or GUI, the error below generates and the pet is not renamed.

I'm testing on 1.21.1, paper build 52, with simple pets build 271.

### Steps To Reproduce

Get a pet 
Either via the GUI or with /pet rename (type of pet) (name), attempt to rename the pet.
Get error below

### Relevant log/error output

```shell
https://paste.gg/p/Momshroom/01db645eb3f344d4a860e67b57a37136
```

### Up-To-Date

- [X] I am using the latest build

**Comment by brainsynder-Dev** [comment]
Thats a strange one... Need to look into this...

**Comment by Chevels** [comment]
Hello ! Same here with latest build.
Have a nice weekend :)

**Comment by Chevels** [comment]
Bump

**Comment by brainsynder-Dev** [comment]
Working on a fix for this

**Comment by Chevels** [comment]
> Working on a fix for this

Hello !
Any news of this fix ?
