### ISSUE TITLE
Uh 1.13 please?

### ISSUE THREAD

**Issue by Lakebighead** [brainsynder-Dev/SimplePets#28]
### What steps will reproduce the problem?
1. idk
2. idk
3.  I just need a 1.13 version so this plugin may run.

### What were you expecting to happen? What happened instead?
Idk
### What version of the plugin are you using? *(Type /version <Plugin Name>)*
Latest
### What Spigot version are you using? *(Type /version)*
1.13
### What plugins are you using? *(Type /plugins)*
A bunch lol?
### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
No, just says SimplePets is not compatible with my version in the console
### Additional information? *(Did it work in previous versions? etc.)*
Yeah, worked when I used 1.12.2

**Comment by brainsynder-Dev** [comment]
Try a development version of SimplePets and SimpleAPI the development versions work on 1.13
You can get them here: https://discord.gg/qGfnAfC

**Comment by brainsynder-Dev** [comment]
http://ci.pluginwiki.us/job/SimplePets/
