### ISSUE TITLE
Link for 1.13 Dev builds?

### ISSUE THREAD

**Issue by JPVortex225** [brainsynder-Dev/SimplePets#29]
### What steps will reproduce the problem?
Plugin dosen't work on 1.13

### What were you expecting to happen? What happened instead?
I wasn't expecting it to work, but I am wondering when it will be updated to 1.13 or have a download to dev builds.
### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
no

**Comment by brainsynder-Dev** [comment]
Try one of the development versions (available on the discord)

**Comment by brainsynder-Dev** [comment]
http://ci.pluginwiki.us/job/SimplePets/
