### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by captnfox** [brainsynder-Dev/SimplePets#32]
### What steps will reproduce the problem?
1.
2.
3. 

### Additional information? *(Did it work in previous versions? etc.)*
hi there! everytime i clikc the download button for this plugin i get time out, and a message says can't reach this site.

**Comment by brainsynder-Dev** [comment]
Could you please go into more detail... "Download Link not working" does not give us much to go off of...

https://pluginwiki.us/download/simplepets/

**Comment by captnfox** [comment]
when i click the download link and a page pop up (as normal) but after a
5-10 sec i get a Message ''This site can't be reached''

error code: ERR_CONNECTION_TIMED_OUT

Den man. 5. nov. 2018 kl. 20:37 skrev brainsynder <notifications@github.com

**Comment by brainsynder-Dev** [comment]
Yea, I believe that is on your end not ours (I have no trouble reaching it on my computer, phone, and tablet)
