### ISSUE TITLE
Various Amount of issues

### ISSUE THREAD

**Issue by AmazedMender16** [brainsynder-Dev/SimplePets#33]
Hello,

Tested the latest build ( Build Number: 17 | Server Version: 1.12.2 ) and found the following:

- Bunnies don't have any walking effects
- Mobs that can fly don't fly around
- Would love to see an option to disable tool tips
- Some pet options don't work https://pastebin.com/EbQgJSN1
- Errors when switching worlds https://pastebin.com/Ly5Bw5Q6

Regards,
Glenn R.

**Comment by brainsynder-Dev** [comment]
Here is an updated list of completed fixes:
_(Will be available in the next Development build)_

- Bunnies don't have any walking effects
- Mobs that can fly don't fly around
- ~~_Would love to see an option to disable tool tips_~~ (We talked about this one via PM)

- ~~_Some pet options don't work pastebin.com/EbQgJSN1_~~ (Now uses a different method to get the skull)

- ~~_Errors when switching worlds pastebin.com/Ly5Bw5Q6_~~
