### ISSUE TITLE
No SimplePets Ordner in my Plugins Ordner (1.8.8)

### ISSUE THREAD

**Issue by MichelSimple** [brainsynder-Dev/SimplePets#34]
### What steps will reproduce the problem?
1. Download the 3.9v for 1.8.8
2. Go in my Plugins Ordner and upload it there
3. reload the Server

### What were you expecting to happen? What happened instead?
      That the Plugin works.                Nothing it does not create a SimplePets Ordner in my Plugin Ordner!

### Could you please do *"/pet debug"* and paste the link here:
Plugin does not work!

### Additional information? *(Did it work in previous versions? etc.)*
I don´t tried it in previous versions.

**Comment by brainsynder-Dev** [comment]
1) Make sure you have SimpleAPI downloaded as well
2) Do not reload your server (restart it)
3) What is Ordner? You mean Folder?

**Comment by MichelSimple** [comment]
I downloaded SimpleAPI as well but there is now only a SimpleAPI Folder and the Plugin SimplePets does not Work! When I do /help SimplePets it says that the command is: /pet

**Comment by brainsynder-Dev** [comment]
Please restart your server and send me the 'latest.log' file so i can see why it is not working

**Comment by MichelSimple** [comment]
https://www.file-upload.net/download-13474114/latest.log.html
