### ISSUE TITLE
Compiled plugin contains PlotSquared code, and causes runtime class conflicts

### ISSUE THREAD

**Issue by Sauilitired** [brainsynder-Dev/SimplePets#35]
### What steps will reproduce the problem?
1. Use the plugin together with PlotSquared
2. ?? Profit

### What were you expecting to happen? What happened instead?
I expected the plugin to not include PlotSquared in the compiled artifact. What happened instead is that it did, and thus caused (not so fun) class conflicts during runtime.

### Could you please do *"/pet debug"* and paste the link here:
I didn't actually run the plugin. I checked the source :man_shrugging: 

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
This was reported by a PlotSquared user, confirmed to be caused by SimplePets:
https://pastebin.com/SvVZfkAs

### Additional information? *(Did it work in previous versions? etc.)*
Here's a git blame: https://github.com/brainsynder-Dev/SimplePets/blame/8880bf7176465382de4d8961020eb8c9a72dcfde/pom.xml#L78

**Comment by Sauilitired** [comment]
Here is me showing the jar content, mostly for effect (insert horror music here :ghost: :skull:)
![Jar content](https://i.imgur.com/fA3bs3I.png)

**Comment by brainsynder-Dev** [comment]
Welp... didn't see that coming...
Fixed it in [2e5f210](https://github.com/brainsynder-Dev/SimplePets/commit/2e5f21092c02ae7da904bc7f0c07724ef1549a05)
