### ISSUE TITLE
Can't summon pet 

### ISSUE THREAD

**Issue by Xardas88** [brainsynder-Dev/SimplePets#36]
### What steps will reproduce the problem?
1.run command /pet summon [namepet]
2.or /pet spawn [namepet]

### What were you expecting to happen? What happened instead?
summon a pet.
getting error on chat and on console

### Could you please do *"/pet debug"* and paste the link here:
https://hastebin.com/idayahixam

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
https://hastebin.com/murokuyoqa.cs

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
yes

### Config
https://hastebin.com/oqulasozib.sql

**Comment by brainsynder-Dev** [comment]
Try the latest [Development Build (# 25)](http://ci.pluginwiki.us/job/SimplePets/25/)
