### ISSUE TITLE
Server Crashing due to SimplePets

### ISSUE THREAD

**Issue by blazex224** [brainsynder-Dev/SimplePets#4]
Hello,
I have not updated the plugin recently, however just this morning, a player has reported that he cannot log back into the server. It seems like every time he logs in, the server crashes. I'm not quite sure what this has to do with SimplePets, but the crash reports show SimplePets.

https://pastebin.com/NGbRqxfB
https://pastebin.com/sD0dnmZf
https://pastebin.com/CyR6C29h

Thanks!

**Comment by brainsynder-Dev** [comment]
Please try the beta versions of SimplePets and SimpleAPI as your issue has been fixed very early on in the beta versions... Download from here: https://discord.gg/qGfnAfC

**Comment by blazex224** [comment]
Thanks a ton, appreciate ya.
