### ISSUE TITLE
Seems to work, but errors in the console 1.12.2

### ISSUE THREAD

**Issue by IITFA** [brainsynder-Dev/SimplePets#41]
### What steps will reproduce the problem?
1. The plugin seems to work, but there are errors in the console.
2.
3. 

### What were you expecting to happen? What happened instead?
Expect there to be no errors.
### Could you please do *"/pet debug"* and paste the link here:
https://hastebin.com/miyuqodili
### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
https://hastebin.com/acilusakut.sql
### Additional information? *(Did it work in previous versions? etc.)*
The plugin seems to work, but there are errors in the console.

**Comment by Thatsmusic99** [comment]
Has been reported a few times on Discord and is fixed. The solution is as follows:

1. Use the latest beta builds here instead of the latest release: http://ci.pluginwiki.us/job/SimplePets/25/
2. If the error persists, delete the Pets folder in the SimplePets plugin folder (inside plugins).
