### ISSUE TITLE
Pets will not spawn as baby by default

### ISSUE THREAD

**Issue by Symphonic3** [brainsynder-Dev/SimplePets#47]
### What steps will reproduce the problem?
1. Going to a pet config
2. Adding "age": "true" to make it baby, from what ive decoded
3. Reloading plugin, pet doesnt spawn as baby by default

### What were you expecting to happen? What happened instead?

pet doesnt spawn as baby by default, i expected it to

### Additional information? *(Did it work in previous versions? etc.)*

How do i get a pet to spawn as baby by default? #

**Comment by brainsynder-Dev** [comment]
This functionality was added in the v5 recode of the plugin
