### ISSUE TITLE
Permission help please

### ISSUE THREAD

**Issue by AggerTV** [brainsynder-Dev/SimplePets#49]
### What steps will reproduce the problem?
1. I don't know how to give players the permission to do /pet
2. I don't know how to give players permission to certain pets only
3. 

### Could you please do *"/pet debug"* and paste the link here:
https://hastebin.com/imeyipofep

**Comment by Thatsmusic99** [comment]
If you want players to open /pet with the default config (I’ve just woken up so I can’t quite remember what it looks like), just give them permission to at least one pet: https://github.com/brainsynder-Dev/SimplePets/wiki/Permissions
