### ISSUE TITLE
Going into Spectator game mode with certain pets leads to server crashes.

### ISSUE THREAD

**Issue by Tehwolf** [brainsynder-Dev/SimplePets#51]
### What steps will reproduce the problem?
1. /pet armorstand
2. /gamemode spectator

### What were you expecting to happen? What happened instead?
Pet entity to vanish, same as other pet entity types when entering spectator.

### Could you please do *"/pet debug"* and paste the link here:
https://puu.sh/Ejg5X.txt

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
https://puu.sh/Ejg2G.txt
https://puu.sh/Ejg2Z.txt

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
Running development build for Spigot 1.14.4, Build 30. Also, effects Build 28.

### Additional information? *(Did it work in previous versions? etc.)*
Did not attempt outside of 1.14.4 Spigot, did not encounter any issues like this in version 4.1, but also did not specifically test for it.

**Comment by Halbgod** [comment]
Tried it and not having this issue on 1.12.2. 
Not to say there is no error, but to close the possibilities from where the error comes.
Somewhere between 1.12.2 and 1.14.4 there has to be an error.

**Comment by Thatsmusic99** [comment]
Not reproduced on 1.15.2 using Build 29.
