### ISSUE TITLE
Silent pets, and pet size?

### ISSUE THREAD

**Issue by AggerTV** [brainsynder-Dev/SimplePets#52]
### What steps will reproduce the problem?
1. How do I force the pets to be silent?
2.How do I force pets to be small? I don't wan't players with big pets running around.
3.

**Comment by AggerTV** [comment]
I would appreciate if you would respond

**Comment by brainsynder-Dev** [comment]
Sorry for the wait, i have been busy and forgot about it.
ATM there is a small hacky way to make this happen... 
in the pet file you want to modify, in the on-summon array... 
add the `pet modify {player} {'silent':true,'baby':true}` command...
Then you would have to remove the players permission to change the pet from silent/baby

**Comment by Thatsmusic99** [comment]
Sorry, Brian’s busy with the plugin and I’m busy with life in general so this went over my head. As of currently, neither is possible.

**Comment by AggerTV** [comment]
> Sorry for the wait, i have been busy and forgot about it.
> ATM there is a small hacky way to make this happen...
> in the pet file you want to modify, in the on-summon array...
> add the `pet modify {player} {'silent':true,'baby':true}` command...
> Then you would have to remove the players permission to change the pet from silent/baby

Could you make an example of this in ex. the cow file?

**Comment by AggerTV** [comment]
It doesn't work
