### ISSUE TITLE
problems with rabbit 

### ISSUE THREAD

**Issue by Darigsey** [brainsynder-Dev/SimplePets#54]
Hi I like to use the plugin SimplePets and wanted to ask if it is known that the rabbit can not jump over blocks and generally no animation has that makes something sad

I use:spigot-1.14.4.jar
and:  SimplePets Build #1 (22.10.2019 21:09:05)

**Comment by Thatsmusic99** [comment]
See http://ci.pluginwiki.us/job/SimplePets/ - the issue was fixed in all versions but 1.13.2 which I will be working on in the future.
