### ISSUE TITLE
Ability to remove pets name tag visibility

### ISSUE THREAD

**Issue by SnekBoyGenius** [brainsynder-Dev/SimplePets#62]
The server I am currently creating is set so that no nametags are visible. But with this plugin, the pet nametags are still visible and there is no way I can see to get rid of there nametags. I tried setting the max character length to 0 but It just stopped me from creating a new name altogether and kept it as its default. 

Is this something you could add or is there another way I can fix this issue? Thanks!

**Comment by Thatsmusic99** [comment]
Will mark as a feature request for the future

**Comment by brainsynder-Dev** [comment]
Added in v5 recode of the plugin
