### ISSUE TITLE
Movement and armor stands

### ISSUE THREAD

**Issue by SirAltF4** [brainsynder-Dev/SimplePets#63]
as soon as you try and ride an armor stand the game crashes, in the most recent build, Also when riding every mob the direction of movement is off. it moves slightly sideways. Otherwise, amazing plugin keep it up

**Comment by Thatsmusic99** [comment]
Could not reproduce on 1.15.2 with Build 29: http://ci.pluginwiki.us/job/SimplePets/30/ (30 was just changes to the plugin.yml)
