### ISSUE TITLE
Pets turn into a pig

### ISSUE THREAD

**Issue by SupreMouse** [brainsynder-Dev/SimplePets#64]
### What steps will reproduce the problem?
1. Go onto the server
2. Select any pet (besides armor stand)
3. Watch it turn into a pig

### What were you expecting to happen? What happened instead?
I clicked on sheep, I was expecting a sheep but got a pig

### Could you please do *"/pet debug"* and paste the link here:
No link came up; it just says "Fetching debug info..." and nothing else happens.

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
https://hastebin.com/ibigixeceb.sql

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
Yes

### Additional information? *(Did it work in previous versions? etc.)*
No additional information.

**Comment by Thatsmusic99** [comment]
No, you haven’t tried the developmental builds, they already fixed this issue: http://ci.pluginwiki.us/job/SimplePets/29/

If that does not work, please provide your full latest.log.
