### ISSUE TITLE
Parrot Movement API Issue

### ISSUE THREAD

**Issue by xMarcusG** [brainsynder-Dev/SimplePets#68]
### What steps will reproduce the problem?
1. Going to /pets
2. Spawning the pet Parrot

### What were you expecting to happen? What happened instead?
Expected: Parrot to walk/fly next to you as you move. Instead: The parrot walls in circles.
https://gyazo.com/822763db0df51c917d68a1b20be7065b

### Could you please do *"/pet debug"* and paste the link here:
No debug link was given, instead spammed console with this once https://pastebin.com/d4cHbrtb

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
Do not have a stacktrace error from this pet, only the pet debug command issues a error in console.

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
Have not tried the development build yet.

### Additional information? *(Did it work in previous versions? etc.)*
I'm not sure for I am using the latest version posted on Spigot, 4.2.1

**Comment by Thatsmusic99** [comment]
Debug command error is known of and fixed considered fixed in the experimental builds (#67) whilst the parrot issue - as well as for other mobs - is being addressed in #33. This issue will not be immediately fixed in the recode but will instead be looked into afterwards.
