### ISSUE TITLE
NPE on PlayerJoinEvent with SimplePets v3.6.6

### ISSUE THREAD

**Issue by Prunt** [brainsynder-Dev/SimplePets#7]
### What steps will reproduce the problem?  
1. Player joins the server
2. Presumably has a pet activated, but I'm not sure

### What were you expecting to happen? What happened instead?  
Expected no errors; got an error.

### What version of the plugin are you using? (Type /version &lt;Plugin Name&gt;)  
SimplePets version 3.6.6

### What Spigot version are you using? (Type /version)  
Paper version git-Paper-1320 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### What plugins are you using? (Type /plugins)
I'd rather not post them publicly.

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). (If you're not sure, upload your whole server log) 
https://hastebin.com/aququyiquc.hs

**Comment by brainsynder-Dev** [comment]
Please try the beta versions of SimplePets and SimpleAPI as your issue has been fixed LONG ago on in v3.7, but due to issues with 3.7 i suggest the betas... Download from here: https://discord.gg/qGfnAf
