### ISSUE TITLE
Development Branch failed to Build

### ISSUE THREAD

**Issue by c0d3rb0y** [brainsynder-Dev/SimplePets#71]
### What steps will reproduce the problem?
1. Run Maven at project location (development branch)

### What were you expecting to happen? What happened instead?
It to build.
### Could you please do *"/pet debug"* and paste the link here:
No because i cant build
### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
[Yes.](https://hastebin.com/puciwebuse.rb)
### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
THIS WAS A DEV BUILD
### Additional information? *(Did it work in previous versions? etc.)*
Uh, it wont build? How does this apply

**Comment by Thatsmusic99** [comment]
Firstly, if you want a dev build, you are free to use http://ci.pluginwiki.us/job/SimplePets-Experimental/12/

The place you’re getting an error at is when Maven is trying to identify the environment variable BUILD_NUMBER. That’s for Jenkins; you can do what I did and replace it.

And also need to mention, your version of Maven looks a bit... old? It’s a little harder to read at least. I will check my own version when I’m out of bed.

**Comment by brainsynder-Dev** [comment]
To get the BUILD_NUMBER you could do this command to compile the plugin
`mvn clean install -f pom.xml -Denv.BUILD_NUMBER=TEST`
`TEST` is the build number I use for testing
