### ISSUE TITLE
PetVehicleEvent not called when a player dismounts their pet using shift

### ISSUE THREAD

**Issue by LlewVallis** [brainsynder-Dev/SimplePets#72]
### What steps will reproduce the problem?
1. Create a simple plugin that listens for the `PetVehicleEvent` and prints a message if it was of type `PetVehicleEvent.Type.Dismount`.
2. Install both this and SimplePets onto a fresh server.
3. Observe that when a player dismounts from their pet using the shift key the event *is not* fired and no message is printed.
4. Observe that when a player dismounts from their pet using the pet GUI the event *is* fired and the message is printed.

A simple plugin that can be used to test this bug can be found here:
[simple-pets-bug-plugin.tar.gz](https://github.com/brainsynder-Dev/SimplePets/files/4969848/simple-pets-bug-plugin.tar.gz)

### What were you expecting to happen? What happened instead?
I was expecting a `PetVehicleEvent` to be fired when a player presses shift to dismount their pet. Instead, the event is only fired if the player uses the GUI to dismount.

### Output of /pet debug
```
{
  "plugins": [
    "PlugMan (2.1.7)",
    "SimplePets (4.3 (build 17))",
    "SimplePetsBug (0.0.0-SNAPSHOT)"
 ],
  "type": "PaperSpigot",
  "info": {
    "bukkit_version": "1.16.1-R0.1-SNAPSHOT",
    "nms_version": "v1_16_R1",
    "java": "14.0",
    "reloaded": false,
    "raw_version": "git-Paper-28 (MC: 1.16.1)",
    "simplepets": "4.3 (build 17)"
  }
}
```

### Do you have a stacktrace error?
Nothing non-standard or of any interest appears in server logs or as an error in game.

### Have you tried one of our development builds?
Yes. I'm using the latest experimental build: v4.3 build 17. I have not tested this in past versions.

**Comment by Thatsmusic99** [comment]
Thank you for the test plugin with this. I'll do some investigating now.

**Comment by LlewVallis** [comment]
If anyone is looking for a work around, `EntityDismountEvent` can be made to work by checking if the dismounting entity is a player and checking if the dismounted entity is said player's pet.

**Comment by Thatsmusic99** [comment]
Will be fixed in an upcoming experimental build
