### ISSUE TITLE
Request: Add Worldguard Flag which prohibits pets from coming inside, or a similiar feature.

### ISSUE THREAD

**Issue by adamromulus** [brainsynder-Dev/SimplePets#74]
I run a large survival server on 1.16.1, I think Simple Pets will be a fantastic addition.

One issue I foresee, is that pets will be following people into spleef matches and races, which can't be allowed to happen.
If there was a way to stop pets from entering certain areas, I would install this right now.

**Comment by Thatsmusic99** [comment]
WorldGuard flags aren't used currently (if I'm honest they're a bit of a pain to work with), but if you take a look in the config.yml file, you're able to stop pets from spawning or being ridden in specified regions (I don't recall these options off the top of my head)

Let us know if this doesn't work.

**Comment by adamromulus** [comment]
Oh okay! 

I assume that prevents them from following you as well?
If it wasn't clear, I haven't installed this yet, I've just been reading up on the features.

**Comment by Thatsmusic99** [comment]
I believe it does, yes.

**Comment by Thatsmusic99** [comment]
Completely forgot this existed, lol... WorldGuard flags were recently added to a recent experimental build at http://ci.pluginwiki.us/job/SimplePets-Experimental/39/ . Going to close this in response.
