### ISSUE TITLE
Armor Stand Pet Item/Armor Duplication

### ISSUE THREAD

**Issue by ninjamaster4427** [brainsynder-Dev/SimplePets#76]
### What steps will reproduce the problem?
1. Equip the armor stand pet.
2. Equip armor/weapons/shield to the armor stand.
3. Teleport using /spawn or an ender pearl or eat a chorus fruit, etc.
4. All of the armor stand equipment enters your inventory while still being removable from the armor stand. (duplicated)

### What were you expecting to happen? What happened instead?
Items should not "pop off" of the armor stand and into the player inventory.

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
No stacktrace error.

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
Using 4.3 (build 19)

### Additional information? *(Did it work in previous versions? etc.)*
This happens regardless of survival/creative gamemode.

**Comment by Thatsmusic99** [comment]
Fixed in the commit referenced above and will be in Experimental Build #/26
