### ISSUE TITLE
Unformatted no-permission message for /pets

### ISSUE THREAD

**Issue by traksag** [brainsynder-Dev/SimplePets#78]
### What steps will reproduce the problem?
1. Set `Needs-Pet-Permission-To-Open-GUI` to true in the config.
2. Make sure you don't have any SimplePet permissions.
3. Execute the /pets command.

### What were you expecting to happen? What happened instead?

I expected a correctly formatted no-permission message, but instead I'm getting white text saying:
> {prefix} &cYou do not have permission.

### Additional information?

I'm testing this on 4.3 (build 24). The issue seems to be caused by the fact that [this](https://github.com/brainsynder-Dev/SimplePets/blob/experimental-unsafe/MAIN/src/main/java/simplepets/brainsynder/storage/files/Messages.java#L50) piece of code has been commented out in the experimental version, while [this](https://github.com/brainsynder-Dev/SimplePets/blob/experimental-unsafe/MAIN/src/main/java/simplepets/brainsynder/menu/inventory/list/SelectionMenu.java#L115) piece of code expects it to delegate `getString(string)` to `getString(string, true)`. The issue can probably be fixed by adding `true` as last argument to the `getString` call.

**Comment by Thatsmusic99** [comment]
Investigating today
