### ISSUE TITLE
Not Initializing on 1.16.3

### ISSUE THREAD

**Issue by GHOSTKJB** [brainsynder-Dev/SimplePets#79]
### What steps will reproduce the problem?
1. Dropped plugin into plugins folder on 1.16.3
2. Booted server
3. Plugin didn't initialize.

### What were you expecting to happen? What happened instead?
I expected it to initialize but internal errors happened.

### Could you please do *"/pet debug"* and paste the link here:
I tried but it gives the same error "an internal error occurred while attempting to perform this command 

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
I don't

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
I joined the server but there wasn't a label if it was for 1.16.3 in the experimental version.

### Additional information? *(Did it work in previous versions? etc.)*
This is my first time trying this plugin.

**Comment by Thatsmusic99** [comment]
Use the 1.16.2 SimplePets experimental build.
