### ISSUE TITLE
Baby Wither Cosmetics

### ISSUE THREAD

**Issue by xSaoul** [brainsynder-Dev/SimplePets#83]
Baby withers nameplate and all particles are too high on the pet. Makes the pet look silly as the particles are showing for a normal wither and the nameplate is 2-3 blocks higher than the pet.

**Comment by brainsynder-Dev** [comment]
Thats because it is a Normal Wither... It is not actually a "Baby Wither". We can not change the height of the name, or the particles as they are coded into MC.
