### ISSUE TITLE
[feature request] RedProtect hook

### ISSUE THREAD

**Issue by DakirDev** [brainsynder-Dev/SimplePets#84]
### What steps will reproduce the problem?
1. Player A goes with his pet into the redprotect claim of player B
2. Player B kicks player A from his claim with the command "/rp kick playerA"

### What were you expecting to happen? What happened instead?
Player A is not kicked from the claim and can still use his pet to ride on the claim of player B.
However, player A should actually be kicked from the claim with his pet and he should not be able to enter it for a certain time (depending on the setting of Redprotect).

### Could you please do *"/pet debug"* and paste the link here:
https://hastebin.com/kuginobeqa

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
Use the latest experimental dev build

### Additional information? *(Did it work in previous versions? etc.)*
The hook required for this is comparable to the PlotSquared Hook

**Comment by Thatsmusic99** [comment]
Is this reproducible without a SimplePets mob, such as riding a horse or pig into the claim?

**Comment by DakirDev** [comment]
yes, if the player is sitting on a normal horse he will be kicked as soon as he continues to move on the claim. So directly after the next PlayerMoveEvent

The bug has already been reported to RedProtect. But probably only possible by a hook in SimplePets.
https://github.com/FabioZumbi12/RedProtect/issues/632

**Comment by Thatsmusic99** [comment]
Will have to look into in the future.
