### ISSUE TITLE
Pet GUI doesn't work

### ISSUE THREAD

**Issue by Altruiis** [brainsynder-Dev/SimplePets#89]
### What steps will reproduce the problem?
1. Install SimplePets 1.16.4 experimental (build 43)
2. Run /pet menu or just /pet
3. Profit

### What were you expecting to happen? What happened instead?
The menu is supposed to open with all the pets and pages, but it doesn't work and sends an error in console (no error message ingame)
### Could you please do *"/pet debug"* and paste the link here:
https://hastebin.com/ecosorozin
### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
https://hastebin.com/udoxilataj.md
### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
Yes, using the latest dev build
### Additional information? *(Did it work in previous versions? etc.)*
It worked in build 38, but does not work now.

**Comment by Tyloon1e** [comment]
Same issue here. Plugin is completely unusable.

**Comment by Thatsmusic99** [comment]
Apologies, I forgot to respond to this; I'm not sure what went wrong with build 43 but please use 42 temporarily.

**Comment by Tyloon1e** [comment]
> Apologies, I forgot to respond to this; I'm not sure what went wrong with build 43 but please use 42 temporarily.

Yes, it works fine! 👍 
When do you plan to release the next big update?
