### ISSUE TITLE
Error Speed

### ISSUE THREAD

**Issue by Stonck** [brainsynder-Dev/SimplePets#9]
### What steps will reproduce the problem?  
1. I change pet speed in config but don't work
2. 
3. 

### What version of the plugin are you using? (Type /version &lt;Plugin Name&gt;)  
3.8
### What Spigot version are you using? (Type /version)  
1.8.8
### What plugins are you using? (Type /plugins)  
X
### Additional information?  *(Are you using a beta version of the plugin? Did it work in previous versions? etc.)*

i put 0.1 but the speed don't change

**Comment by brainsynder-Dev** [comment]
As of v3.7 (or v3.8 I cant remember) the customization of the speed was temp. disabled due to issues with pets randomly not moving when the speed value was changes, It will be added back once i get it fixed.

**Comment by Stonck** [comment]
How long do you want to launch a new update?

**Comment by Foorack** [comment]
@Stonck I just tested and both `WalkSpeed` and `RideSpeed` works in version 3.9. If you haven't already can you please update to that?

@brainsynder-Dev Can this issue be closed as Resolved?
