### ISSUE TITLE
How to stop the message reminding you to update everytime you join

### ISSUE THREAD

**Issue by abyus** [brainsynder-Dev/SimplePets#92]
Everytime I join the server it tells me I should updated simple pets and skript. How do I disable this message?

https://hastebin.com/ucenodomef

**Comment by brainsynder-Dev** [comment]
in the latest Jenkins build if you just look in the config and change `Update-Checking.Message-On-Join` to false
This option is ONLY in Jenkins build 55 and up...
http://ci.pluginwiki.us/job/SimplePets-Experimental/55/
