### ISSUE TITLE
[Feature Request] Spider Wall Climbing (v5)

### ISSUE THREAD

**Issue by Nezz202** [brainsynder-Dev/SimplePets#97]
### What steps will reproduce the problem?
1. Ride spider, then take spider to wall
2. Walk into wall, whilst pressing space
3. Spider jumps :(

### What were you expecting to happen? What happened instead?
Spider climbs wall. Spider didn't climb wall.

### Could you please do *"/pet debug"* and paste the link here:
https://gist.github.com/Nezz202/f11d93accbe11233fd30728abe69d065

### Do you have a stacktrace error? Use [hastebin.com](http://hastebin.com). *(If you're not sure, upload your whole server log)*
No D:

### Have you tried one of our development builds? *(If no, then please check if there is one [here](https://discord.gg/9kqYDaV) and give it a try)*: 
Dev Build - 60

### Additional information? *(Did it work in previous versions? etc.)*
Feature Request - It would be cool if spiders (and cave ones) could climb walls, like they do naturally in the wild. It would allow some cool uses if you could do this whilst riding them.

**Comment by brainsynder-Dev** [comment]
This has been added in the v5 recode of the plugin
